HANDLE_REGISTER_(REG_AX, "ax")
HANDLE_REGISTER_(REG_BX, "bx")
HANDLE_REGISTER_(REG_CX, "cx")
HANDLE_REGISTER_(REG_DX, "dx")

HANDLE_REGISTER_(REG_R0, "r0")
HANDLE_REGISTER_(REG_R1, "r1")
HANDLE_REGISTER_(REG_R2, "r2")
HANDLE_REGISTER_(REG_R3, "r3")

//HANDLE_REGISTER_(REG_AH, "ah")
//HANDLE_REGISTER_(REG_BH, "bh")
//HANDLE_REGISTER_(REG_CH, "ch")
//HANDLE_REGISTER_(REG_DH, "dh")

//HANDLE_REGISTER_(REG_AL, "al")
//HANDLE_REGISTER_(REG_BL, "bl")
//HANDLE_REGISTER_(REG_CL, "cl")
//HANDLE_REGISTER_(REG_DL, "dl")

//HANDLE_REGISTER_(REG_DI, "di")
//HANDLE_REGISTER_(REG_SI, "si")
//HANDLE_REGISTER_(REG_BP, "bp")
//HANDLE_REGISTER_(REG_SP, "sp")

